// src/constants/books.ts

export const DUMMY_BOOKS = [
  {
    id: 1,
    title: "Laskar Pelangi",
    mainAuthor: "Andrea Hirata",
    category: "Novel",
    availability: 5,
    imageUrl: "/images/book1.png",
    description: "Kisah perjuangan sepuluh anak di Belitong yang bersekolah di sebuah SD Muhammadiyah yang kondisinya sangat memprihatinkan.",
    isbn: "978-979-3062-79-1",
    publisher: "Bentang Pustaka",
    year: "2005",
    language: "Indonesia",
  },
  {
    id: 2,
    title: "Clean Code",
    mainAuthor: "Robert C. Martin",
    category: "Teknologi",
    availability: 0,
    imageUrl: "/images/book2.png",
    description: "Buku wajib bagi software engineer untuk memahami cara menulis kode yang mudah dibaca dan dikelola.",
    isbn: "978-0132350884",
    publisher: "Prentice Hall",
    year: "2008",
    language: "Inggris",
  },
  {
    id: 3,
    title: "Filosofi Teras",
    mainAuthor: "Henry Manampiring",
    category: "Self-Development",
    availability: 2,
    imageUrl: "/images/book3.png",
    description: "Filsafat Yunani-Romawi kuno Stoisisme untuk mental tangguh di masa kini.",
    isbn: "978-602-412-518-9",
    publisher: "Penerbit Buku Kompas",
    year: "2018",
    language: "Indonesia",
  },
  {
    id: 4,
    title: "Atomic Habits",
    mainAuthor: "James Clear",
    category: "Self-Development",
    availability: 10,
    imageUrl: "/images/book4.png",
    description: "Cara mudah untuk membangun kebiasaan baik dan menghilangkan kebiasaan buruk.",
    isbn: "978-0735211292",
    publisher: "Penguin Random House",
    year: "2018",
    language: "Inggris",
  },
  {
    id: 5,
    title: "The Pragmatic Programmer",
    mainAuthor: "Andrew Hunt & David Thomas",
    category: "Teknologi",
    availability: 3,
    imageUrl: "/images/book5.png",
    description: "Salah satu buku pemrograman paling berpengaruh yang mencakup segala hal dari tanggung jawab pribadi hingga pengembangan karier.",
    isbn: "978-0135957059",
    publisher: "Addison-Wesley Professional",
    year: "2019",
    language: "Inggris",
  },
  {
    id: 6,
    title: "Bumi",
    mainAuthor: "Tere Liye",
    category: "Novel",
    availability: 7,
    imageUrl: "/images/book6.png",
    description: "Petualangan tiga sahabat di dunia paralel yang penuh dengan keajaiban dan teknologi canggih.",
    isbn: "978-602-03-0112-9",
    publisher: "Gramedia Pustaka Utama",
    year: "2014",
    language: "Indonesia",
  },
  {
    id: 7,
    title: "Sapiens: Riwayat Singkat Umat Manusia",
    mainAuthor: "Yuval Noah Harari",
    category: "Sejarah",
    availability: 4,
    imageUrl: "/images/book7.png",
    description: "Menjelajahi bagaimana manusia berevolusi dari spesies yang tidak berarti menjadi penguasa planet Bumi.",
    isbn: "978-602-440-035-4",
    publisher: "KPG",
    year: "2011",
    language: "Indonesia",
  },
  {
    id: 8,
    title: "You Don't Know JS",
    mainAuthor: "Kyle Simpson",
    category: "Teknologi",
    availability: 0,
    imageUrl: "/images/book8.png",
    description: "Seri buku yang mendalami mekanisme inti bahasa JavaScript secara mendalam.",
    isbn: "978-1491904244",
    publisher: "O'Reilly Media",
    year: "2015",
    language: "Inggris",
  },
  {
    id: 9,
    title: "Rich Dad Poor Dad",
    mainAuthor: "Robert Kiyosaki",
    category: "Finansial",
    availability: 6,
    imageUrl: "/images/book9.png",
    description: "Buku yang mengubah cara jutaan orang di seluruh dunia berpikir tentang uang dan investasi.",
    isbn: "978-1612680194",
    publisher: "Plata Publishing",
    year: "1997",
    language: "Inggris",
  },
  {
    id: 10,
    title: "Psychology of Money",
    mainAuthor: "Morgan Housel",
    category: "Finansial",
    availability: 8,
    imageUrl: "/images/book10.png",
    description: "Buku yang mengeksplorasi cara orang berpikir tentang uang dan keputusan finansial mereka.",
    isbn: "978-0857197689",
    publisher: "Harriman House",
    year: "2020",
    language: "Inggris",
  },
  {
    id: 11,
    title: "Norwegian Wood",
    mainAuthor: "Haruki Murakami",
    category: "Novel",
    availability: 2,
    imageUrl: "/images/book11.png",
    description: "Novel coming-of-age yang menyentuh tema cinta, kehilangan, dan pencarian diri.",
    isbn: "978-0099448822",
    publisher: "Vintage",
    year: "1987",
    language: "Inggris",
  },
  {
    id: 12,
    title: "Design Patterns",
    mainAuthor: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    category: "Teknologi",
    availability: 1,
    imageUrl: "/images/book12.png",
    description: "Kumpulan pola desain perangkat lunak yang sering digunakan dalam pengembangan berorientasi objek.",
    isbn: "978-0201633610",
    publisher: "Addison-Wesley",
    year: "1994",
    language: "Inggris",
  },
  {
    id: 13,
    title: "The Alchemist",
    mainAuthor: "Paulo Coelho",
    category: "Novel",
    availability: 9,
    imageUrl: "/images/book13.png",
    description: "Fabel modern tentang mengikuti impian dan makna kehidupan.",
    isbn: "978-0061122415",
    publisher: "HarperCollins",
    year: "1988",
    language: "Inggris",
  },
  {
    id: 14,
    title: "Thinking, Fast and Slow",
    mainAuthor: "Daniel Kahneman",
    category: "Psikologi",
    availability: 0,
    imageUrl: "/images/book14.png",
    description: "Penjelasan dua sistem berpikir manusia dan bagaimana keduanya mempengaruhi keputusan.",
    isbn: "978-0374533557",
    publisher: "Farrar, Straus and Giroux",
    year: "2011",
    language: "Inggris",
  },
  {
    id: 15,
    title: "Man's Search for Meaning",
    mainAuthor: "Viktor E. Frankl",
    category: "Psikologi",
    availability: 4,
    imageUrl: "/images/book15.png",
    description: "Catatan pengalaman dan pemikiran seorang psikiater di kamp konsentrasi dan pentingnya menemukan makna.",
    isbn: "978-0241950364",
    publisher: "Penguin Books",
    year: "1946",
    language: "Inggris",
  },
];